n = -1:1;
x = [1, 3, -2];
x_fold = [-2, 3, 1]; 
xe = 0.5 * (x + x_fold);
xo = 0.5 * (x - x_fold);
subplot(3, 1, 1);
plot2d3(n, x);
title('Signal x(n)'); xlabel('n'); ylabel('Amplitude');
subplot(3, 1, 2);
plot2d3(n, xe);
title('Even component xe(n)'); xlabel('n'); ylabel('Amplitude');
subplot(3, 1, 3);
plot2d3(n, xo);
title('Odd component xo(n)'); xlabel('n'); ylabel('Amplitude');
